####  Source global definitions

if [ -f /etc/bashrc ]; then
	source /etc/bashrc
fi

#### History

# save as much history as we can
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=ignoredups               # ignore same lines if they go successively
export HISTTIMEFORMAT='%y-%m-%d %H:%M:%S> ' # add timestamps near all commands
shopt -s histappend                         # do not overwrite history files from different sessions - append
shopt -s cmdhist                            # combine lines of multiline command by adding semicolons there necessary

#### Additional setting

# Fix minor erros in path while using cd builtin
shopt -s cdspell

#### Common settings

source <(~/configs/shells/common.bash bash)

export PATH="$HOME/.cargo/bin:$PATH"
