#!/bin/bash

CLEAR="$(printf '\e[0m')"
GREEN="$(printf '\e[1;32m')"
PURPLE="$(printf '\e[0;35m')"

grep --with-filename --line-number --color=always "$@" \
	| sed -e 's/^(standard input):[[:digit:]]*://g' \
	| sed -e 's/^\([^[:space:]]*\):\([[:digit:]]*\):/'"$GREEN"'\1'"$CLEAR"':'"$PURPLE"'\2'"$CLEAR"': /g' # filename is not colored on all platforms
