#!/bin/bash

CLEAR="$(printf '\e[0m')"
GREEN="$(printf '\e[1;32m')"
PURPLE="$(printf '\e[0;35m')"

additionalColoring="sed -e 's/^\\([^[:space:]]*\\):\\([[:digit:]]*\\):/${GREEN}\\1${CLEAR}:${PURPLE}\\2${CLEAR}: /g'" # filename is not colored on all platforms
for arg in "$@"; do
	if [ "$arg" = '--color=never' ]; then
		additionalColoring='cat'
	fi
done

excludes="$(awk -- "/^#|^$/{next}/\/$/{printf \"--exclude-dir=%s \", substr(\$0, 0, length(\$0) - 1);next}{printf \"--exclude=%s \", \$0}" ~/configs/ignores)"

grep --with-filename --line-number --color=always --ignore-case -I $excludes "$@" \
	| sed -e 's/^(standard input):[[:digit:]]*://g' \
	| eval "$additionalColoring"
