#!/bin/sh

nextwindownr () {
	windownr=`expr $windownr + 1`
}
session='arturasl_tmux'

cd

tmux -2 start-server
windownr=1
tmux new-session -d -s ${session} -n 'files' 'ranger'

for i in `seq 1 4`; do
	nextwindownr
	tmux new-window -t ${session}:${windownr}
done

nextwindownr
tmux new-window -t ${session}:${windownr} -n 'news' 'podbeuter'
tmux split-window -v -p 90 -t ${session}:${windownr} 'newsbeuter'

nextwindownr
tmux new-window -t ${session}:${windownr} -n 'mail' '~/configs/scripts/mutt-run.bash gml'
tmux split-window -v -p 50 -t ${session}:${windownr} '~/configs/scripts/mutt-run.bash mit'
tmux split-window -h -p 50 -t ${session}:${windownr} '~/configs/scripts/mutt-run.bash lap'
tmux select-pane -U -t ${session}:${windownr}

nextwindownr
tmux new-window -t ${session}:${windownr} -n 'todo' '~/configs/scripts/exec-on-connection.bash rtm'

nextwindownr
tmux new-window -t ${session}:${windownr} -n 'weechat' 'weechat'

nextwindownr
tmux new-window -t ${session}:${windownr} -n 'htop' 'htop'

tmux select-window -t ${session}:1
tmux -2 attach-session -t ${session}
