#!/bin/bash -e

input_file="$1"
lang=EN-US

if grep --quiet ' \(ir\|bei\|arba\|tačiau\|Pagarbiai\) \|, \(kad\|nes|bet\|o\) \|[ąčęėįšųūž]' "$input_file"; then
	lang=LT
fi

run_language_tool_server_if_needed() {
    if lsof -i tcp@localhost:8081 &>/dev/null; then
        return
    fi

    language_check_path=''
    for py in python python3 python2; do
        language_check_path="$(
        "$py" <<EOF
try:
    import language_check
    print(language_check.__file__)
except:
    pass
EOF
    )"
        if [ -n "$language_check_path" ]; then
            language_check_path="$(dirname "$language_check_path")"
            break
        fi
    done

    if [ -z "$language_check_path" ]; then
        echo "could not find language check" &1>&2
        exit 1
    fi


    java \
        -cp $language_check_path/LanguageTool-*/languagetool-server.jar \
        org.languagetool.server.HTTPServer \
        --port 8081 &>/dev/null &
    disown %1
}

clean_input() {
	cat \
   `# markdown fences` \
	| awk '/^``/{i++;print"";next}{if(i%2){print""}else{print}}'  \
	`# replace things between $$ and \`\` with Xxxx of an appropriate length ` \
	| perl -pe 's/\$(.+?)\$/"X" . "x" x (length($1) + 2 - 1)/ge' \
	| perl -pe 's/`(.+?)`/"X" . "x" x (length($1) + 2 - 1)/ge' \
    `# mail headers` \
	| sed -E -e 's/^(Date|CC|BCC|From|To|Subject|X-Mailer): .*$//g' \
    `# mail comments` \
	| sed -e 's/^>.*//g' \
    `# latex stuff` \
	| detex -cn \
    `# just to make copy pasting easier.` \
	| cat
}

run_language_tool_server_if_needed

cat "$input_file" | clean_input
exit 0

language-check \
	--language "$lang" \
	--disable WHITESPACE_RULE <(\
		cat "$input_file" | clean_input \
	) | sed -e 's/^[^:]*:/'"$(echo "$1" | sed -e 's/[\/&]/\\&/g')"':/g'
