#!/bin/sh

if [ "$1" = "-l" ]; then
	# execute command (with arguments) specified after -l
	shift

	[ "$1" != /bin/bash ] && exec "${@}"
fi

# have no idea that to do :/ - call shell
if which fish >/dev/null; then
	exec fish
else
	exec bash
fi
